### ISSUE TITLE
MIUI 14 安卓13依旧闪退

### ISSUE THREAD

**Issue by sanshu-rom** [tv-player/apks#20]
MIUI14 安卓13望修复

**Comment by tv-player** [comment]
安装1.5.5 试试

**Comment by sanshu-rom** [comment]
1.5.5也一样
已经更新过了

**Comment by tv-player** [comment]
https://raw.githubusercontent.com/tv-player/js-source/1.5.6/app.apk

1.5.5地址已经被封，下载新版试试

**Comment by sanshu-rom** [comment]
java.lang.RuntimeException: Canvas: trying to draw too large(112896000bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at android.view.View.getDrawableRenderNode(View.java:23820)
	at android.view.View.drawBackground(View.java:23741)
	at android.view.View.draw(View.java:23475)
	at com.android.internal.policy.DecorView.draw(DecorView.java:894)
	at android.view.View.updateDisplayListIfDirty(View.java:22308)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4987)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4676)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3873)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2574)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9649)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1386)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by tv-player** [comment]
收到  下版本修复

**Comment by tv-player** [comment]
版本2.0 已修复
